name: borg
description: Dart borg is a command-line tool to support development teams working on large scale Dart and Flutter mono repositories.
version: 1.4.3
homepage: https://github.com/alexei-sintotski/dart-borg

executables:
  borg: main

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.0
  collection: ^1.14.0
  functional_data: ^0.3.0
  glob: ^1.2.0
  json2yaml: ^1.0.0
  meta: ^1.1.0
  path: ^1.6.0
  plain_optional: ^0.1.0
  pubspec_lock: ^2.0.0
  pubspec_yaml: ^2.0.0
  yaml: ^2.2.0

dev_dependencies:
  build_runner: ^1.9.0
  dependency_validator: ^1.4.0
  functional_data_generator: ^0.3.0
  test: ^1.14.0
  test_coverage: ^0.4.0
